import Link from "next/link";
import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { requireSession } from "@/libraries/Auth";
import { connectDatabase } from "@/database/sequelize";
import { AuthComponent } from "@/components/AuthComponent";
import { AccessDenied } from "@/components/AccessDenied";
import { DocumentTemplateGetUseCase } from "@/app/base/useCases/documentTemplate/DocumentTemplateGetUseCase";
import { ValidateDocumentTemplateButton } from "@/app/base/components/documentTemplate/ValidateDocumentTemplateButton";
export const metadata: Metadata = { title: "Document template | VortexGin" };
export default async function Page({ params }: { params: Promise<{ uuid: string }> }) { const session = await requireSession(); await connectDatabase(); let row; try { row = await new DocumentTemplateGetUseCase().exec((await params).uuid, session.user as any); } catch { notFound(); } return <AuthComponent user={session.user} permissions={session.permissions} allowedPermissions={["base:document-template:view:detail"]} accessDeniedComponent={<AccessDenied />}><main className="min-h-screen px-4 py-8"><div className="mx-auto max-w-2xl rounded-[28px] border border-slate-200 bg-white/90 p-6 sm:p-8"><p className="text-sm font-medium uppercase tracking-[0.2em] text-blue-600">Template</p><h1 className="mt-2 text-2xl font-semibold">{row.name}</h1><dl className="mt-6 space-y-3 text-sm"><div><dt className="text-slate-500">Type</dt><dd>{row.document_type}</dd></div><div><dt className="text-slate-500">Google document ID</dt><dd className="break-all font-mono">{row.google_doc_id}</dd></div><div><dt className="text-slate-500">Status</dt><dd>{row.status}</dd></div></dl><div className="mt-6 flex flex-wrap gap-3"><Link href="/base/views/document-templates" className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm">Back</Link><AuthComponent user={session.user} permissions={session.permissions} allowedPermissions={["base:document-template:view:update"]}><Link href={`/base/views/document-templates/${row.uuid}/edit`} className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm text-white">Edit</Link></AuthComponent><AuthComponent user={session.user} permissions={session.permissions} allowedPermissions={["base:document-template:view:validate"]}><ValidateDocumentTemplateButton uuid={row.uuid} /></AuthComponent></div></div></main></AuthComponent>; }
